[package]
name = "jjoner_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.6"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
